export const home = '/'
export const jsonSorter = '/jsonsorter'
export const urlInterpreter = '/urlinterpreter'
export const colorClarifier = '/colorclarifier'
export const textConverter = '/textconverter'
export const keyCodeRevealer = '/keycoderevealer'
